export const PURCHASE_ATTEMPT = 'PURCHASE_ATTEMPT_COMMAND';

export const CREATE_ORDER = 'CREATE_ORDER_COMMAND';
export const ORDER_CREATED = 'ORDER_CREATED_COMMAND';

export const RESERVE_ITEM = 'RESERVE_ITEM_COMMAND';
export const ITEM_RESERVED = 'ITEM_RESERVED_COMMAND';
export const ITEM_OUT_OF_STOCK = 'ITEM_OUT_OF_STOCK_COMMAND';

export const REQUEST_PAYMENT = 'REQUEST_PAYMENT_COMMAND';
export const PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED_COMMAND';
export const PAYMENT_DECLINED = 'PAYMENT_DECLINED_COMMAND';

export const DELIVER_ORDER = 'DELIVER_ORDER_COMMAND';
export const ORDER_DELIVERED = 'ORDER_DELIVERED_COMMAND';
export const ORDER_NOT_DELIVERED = 'ORDER_NOT_DELIVERED_COMMAND';

export const UPDATE_STATISTICS = 'UPDATE_STATISTICS_COMMAND'